<div class="container" style="width: 80%;">
<span style="display:inline-block; width: 80px;"></span>
<div class="field field-name-body field-type-text-with-summary field-label-hidden"><div class="field-items"><div class="field-item even" property="content:encoded"><p><span style="color:#ff8c00;"><strong>Health</strong></span></p>
<p align="justify">NGO’s health care initiatives aim to dispel myths and overcome discrimination in the health sector, as well as increase demand for and improve access to essential services. NGO works to promote essential newborn care and immunisation, reduce malnutrition in children, decrease infant and maternal mortality rates, and protect those affected by. NGO works within the most vulnerable communities, providing reliable information and support that addresses the emotional and medical needs of affected families.</p>
<p align="justify">In support of health care reform, NGO helps ensure accountability in government programmes, increased water and sanitation services and sustained cooperation among health, nutrition, water, and sanitation service providers.</p>
<p align="justify"><span style="color:#ff8c00;"><strong>Education</strong></span></p>
<p align="justify">NGO’s education programme challenges the barriers that exclude girls from learning. NGO works to help girls complete primary education and access formal schools, provides onsite academic support to enhance the quality of teaching, and nurtures leadership skills amongst girls. NGO also supports social learning, which encourages students to explore complex issues like gender through dialogue, role-play, games, and projects.</p>
<p align="justify">NGO provides technical support to teachers and government departments, helps nurture school-community relationships, and offers alternative education opportunities for women and adolescents who never enrolled or did not complete their studies. These alternative education programmes emphasise science, technology, and mathematics, and challenge teachers, students, and parents to critically consider their beliefs.</p>
<p align="justify"><span style="color:#ff8c00;"><strong>Community </strong></span></p>
Many people including those of the new generation who wish to work to make social changes and for social welfare want to form and register NGOs so they can work in their relevant fields and the new NGOs and working NGOs which need financial support from the Government and private funding agencies so they can implement their concepts. NGOs India team and resource centre have been helping and supporting such persons who wish to form NGOs and want economical and other support with he help of projects and other support. At the online resource centre information regarding Funding agencies, Funding Schemes, Funding projects and Funding and other resourceful material regarding running, managing and implementation of concepts of social change by achieving funding and support of Volunteers is available and being updated from time to time.
</div></div></div><span property="dc:title" content="WHAT WE DO" class="rdf-meta element-hidden"></span>
</div>

   